### Create New User
POST http://localhost:3000/api/users
Accept: application/json
Content-Type: application/json

{
  "username" : "pzn",
  "password" : "rahasia",
  "name" : "Programmer Zaman Now"
}

### Login User
POST http://localhost:3000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "username" : "pzn",
  "password" : "rahasia"
}

### Get User API
GET http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMxMDc3MjMsInVzZXJuYW1lIjoicHpuIn0.rvm2zaZFBQ0dt7xbipVZC9UWCH4GnI3z3WOJhN9x9wA

### Update User API
PATCH http://localhost:3000/api/users/current
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMxMDc3MjMsInVzZXJuYW1lIjoicHpuIn0.rvm2zaZFBQ0dt7xbipVZC9UWCH4GnI3z3WOJhN9x9wA
Content-Type: application/json

{
  "name" : "Programmer Zaman Now Lagi",
  "password" : "new password"
}

### Logout User API
DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMxMDc3MjMsInVzZXJuYW1lIjoicHpuIn0.rvm2zaZFBQ0dt7xbipVZC9UWCH4GnI3z3WOJhN9x9wA

