### Create New User
POST http://localhost:3000/api/users
Accept: application/json
Content-Type: application/json

{
  "username" : "pzn",
  "password" : "rahasia",
  "name" : "Programmer Zaman Now"
}

### Login User
POST http://localhost:3000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "username" : "pzn",
  "password" : "rahasia"
}

### Get User API
GET http://localhost:3000/api/users/current
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMwNDIxODEsInVzZXJuYW1lIjoicHpuIn0.5mniGjWCUvhSV6xDdAEm1uuxRaR6mcVDZKiVvy3JpJ8