### Create New User
POST http://localhost:3000/api/users
Accept: application/json
Content-Type: application/json

{
  "username" : "pzn",
  "password" : "rahasia",
  "name" : "Programmer Zaman Now"
}

### Login User
POST http://localhost:3000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "username" : "pzn",
  "password" : "rahasia"
}

### Get User API
GET http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMxNzg5NTUsInVzZXJuYW1lIjoicHpuIn0.YG9ZihkGGrO83mDi2swfQxwDUxNu8UkkCiSJsghtQEM

### Update User API
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMxNzg5NTUsInVzZXJuYW1lIjoicHpuIn0.YG9ZihkGGrO83mDi2swfQxwDUxNu8UkkCiSJsghtQEM

{
  "name" : "Programmer Zaman Now Lagi",
  "password" : "new password"
}

### Logout User API
DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMxNzg5NTUsInVzZXJuYW1lIjoicHpuIn0.YG9ZihkGGrO83mDi2swfQxwDUxNu8UkkCiSJsghtQEM

### Create Contact API
POST http://localhost:3000/api/contacts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMyNDQ2MDksInVzZXJuYW1lIjoicHpuIn0.eEc-H7bxdezj09rWp7GewJB9ZKq6BoZDzNo3zeGLdqs

{
  "first_name" : "Eko",
  "last_name" : "Khannedy",
  "email" : "eko@pzn.com",
  "phone" : "32423423434"
}